### PR TITLE
#14: Add OpenAPI docs

### PR DESCRIPTION
**Pull request by j4ng5y**
Add OpenAPI docs based on what I found in server.go

Provided both yaml/json files

### CODE REVIEW

**Comment by localleon** [comment]
We should probably also include some information in the README on how to use the OpenAPI specification. Then we could get rid of the big code block describing the parametrs

**Comment by localleon** [comment]
This is a good start and i will finish it myself. Thank you very much.

**Comment by j4ng5y** [comment]
Sorry, I didn't see the questions right away :D, but as far as your json/yaml, I like to have both (and if you use VSCode it's super easy to generate both after you write one). Personally, I think the yaml is far more readable, but certain API tools only accept the JSON version (e.g. -- Amazon API Gateway)

**Comment by j4ng5y** [comment]
If you know all of the parameters, then yes, by all means add them to the spec. I was just going off of code and it wasn't entirely clear 😄

**Comment by j4ng5y** [comment]
Also, If you want, I can help with to clean the code up as well to make it a little easier to maintain.

**Comment by localleon** [comment]
Hello @j4ng5y ,

thank you for your answers! :+1:  . Sorry that i answer that late.

> Also, If you want, I can help with to clean the code up as well to make it a little easier to maintain.

I'm open for suggestions. I'd like to remove the `gorilla/mux` and replace it with `net/http`


> If you know all of the parameters, then yes, by all means add them to the spec. I was just going off of code and it wasn't entirely clear smile

Your PR was a great starting point! I added all the parameters to the spec
>  Personally, I think the yaml is far more readable, but certain API tools only accept the JSON version 

After some reading i decided on YAML. Converting it is super easy with online tools so we don't really need to provide it.

Greetings

**Pull request merged**
